GENERAR UN TRAIT QUE SE LLAME CALCULO QUE TENGA UNA FUNCION QUE RECIBA 3 PARAMETROS
PORCENTAJE
NOTAS 0 A 10

ESA FUNCION TIENE QUE DEVOLVER UNA PALABRE, LIBRE, REG, O PROMOCION
SI EL PORCNETAJE ES >=80 && PROMEDIO NOTAS > 8 PROMOCION
SI EL PORCENTAJE <=80 Y 50 >= Y PROMEDIO NOTAS >= 6 REGULKAR
SI EL PORCENTAJE <50 O PROMEDIONOTAS <6 LIBER
